---
- name: NodeJS prerequisites
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

- name: Install NodeJS
  sudo: yes
  apt: pkg=nodejs state=latest

- name: Install build tools
  sudo: yes
  apt: pkg=build-essential state=latest

- name: Install PM2
  sudo: yes
  npm: name=pm2 global=yes state=latest

- name: Install Gulp
  sudo: yes
  npm: name=gulp global=yes

- name: Install Bower
  sudo: yes
  npm: name=bower global=yes

- name: Install Git
  sudo: yes
  apt: pkg=git state=latest

- name: Install app dependencies
  npm: path=/var/www/tcp production=no

- name: Install app dependencies (Bower)
  bower: path=/var/www/tcp

- name: Run app
  shell: pm2 start ecosystem.json
  args:
    chdir: /var/www/tcp
