---
- name: NodeJS prerequisites
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

- name: Install NodeJS
  become: yes
  apt: pkg=nodejs state=latest

- name: Install build tools
  become: yes
  apt: pkg=build-essential state=latest

- name: Configure NPM
  shell: mkdir -p ~/.npm-global && npm config set prefix ~/.npm-global

- name: Configure env path
  lineinfile: dest=~/.profile state=present line="export PATH=~/.npm-global/bin:$PATH"

# temporary workaround (https://github.com/ansible/ansible-modules-extras/issues/1375#issuecomment-186512824)
- name: Install PM2
  npm: name=pm2 global=yes state=present

- name: Update PM2
  npm: name=pm2 global=yes state=latest

# temporary workaround (https://github.com/ansible/ansible-modules-extras/issues/1375#issuecomment-186512824)
- name: Install Sails
  npm: name=sails global=yes state=present

- name: Update Sails
  npm: name=sails global=yes state=latest

- name: Install Git
  become: yes
  apt: pkg=git state=latest

- name: Install app dependencies
  npm: path=/var/www/api production=no

- name: Run app
  shell: PATH=~/.npm-global/bin:$PATH && pm2 start ecosystem.json
  args:
    chdir: /var/www/api
